spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3307/profile?characterEncoding=UTF-8&serverTimezone=UTC
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

